[package]
name = "splashsurf_lib"
version = "0.3.0"
authors = ["Fabian Löschner <loeschner@cs.rwth-aachen.de>"]
license = "MIT"
description = "Library for surface reconstruction of SPH particle data"
keywords = ["sph", "particle", "surface", "reconstruction", "marching-cubes"]
categories = ["graphics", "science", "simulation", "visualization", "rendering"]
readme = "README.md"
edition = "2018"

homepage = "https://github.com/w1th0utnam3/splashsurf"
repository = "https://github.com/w1th0utnam3/splashsurf"
documentation = "https://docs.rs/splashsurf_lib"

# Ignore the tests (especially the test mesh files) for publishing
exclude = [
    "tests/*",
]

[features]
default = []
vtk_extras = ["vtkio"]
profiling = ["coarse-prof"]

[dependencies]
log = "0.4"
nalgebra = "0.21"
num = "0.3"
anyhow = "1.0"
thiserror = "1.0"
coarse-prof = { version = "0.2", optional = true }
itertools = "0.9"
rayon = "1.5"
dashmap = "3.11"
fxhash = "0.2"
vtkio = { version = "0.5", optional = true }
thread_local = "1.0"
num_cpus = "1.13"
